spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://118.24.14.231/iot?characterEncoding=utf-8&useSSL=false
  redis:
    host: 118.24.14.231
    port: 6379

  jpa:
    show-sql: true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null


server:
    context-path: /iot

socket:
  Udpport: 10000
  Tcpport: 10001
